# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('..'))

autodoc_mock_imports = ['matplotlib', 'numba', 'numpy', 'scipy', 'cupy']


# -- Project information -----------------------------------------------------

project = 'LCODE 3D'
author = 'Ivan Kargapolov, Konstantin Lotov, Irina Shalimova, Alexander Sosedkin'
copyright = '2019, ' + author

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.todo',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'matplotlib.sphinxext.plot_directive',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'
# Pull off a hack and substitute different indices
def copy_master_doc(apps):
    import shutil
    if apps.tags.has('html'):
        shutil.copy('index-html.rst', 'index.rst')
    else:
        shutil.copy('index-nonhtml.rst', 'index.rst')
def setup(app):
    app.connect('builder-inited', copy_master_doc)


# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
#html_theme_options = {
#    'navigation_depth': 4,
#    'collapse_navigation': False,
#}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'LCODE3Ddoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    'pointsize': '12pt',


    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',

    'extraclassoptions': 'openany,oneside',

    'preamble': r'''
        \setcounter{tocdepth}{1}
        \setcounter{secnumdepth}{1}
        \let\stdchapter\chapter
        \renewcommand\chapter{\cleardoublepage\stdchapter}
        \let\stdsection\section
        \renewcommand\section{\newpage\stdsection}
    ''',
    #\newcommand{\chapterbreak}{\clearpage}
    #\newcommand{\sectionbreak}{\clearpage}
    #\titlespacing{\chapter}{0em}{*0}{*0}
    #\usepackage{anonchap}
    #\titleformat{\chapter}[hang]{\Huge\bfseries}{\thechapter\hspace{.5em}{|}\hspace{.5em}}{0pt}{\Huge\bfseries}
    #'fncychap': '',
    #'passoptionstopackages': r'\PassOptionsToPackage{compact,tiny}{titlesec}',

    'sphinxsetup': 'hmargin=.5in, vmargin=.75in, marginpar=0in',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'LCODE3D.tex', 'LCODE 3D Documentation',
     'I. Kargapolov, K. Lotov, I. Shalimova, A. Sosedkin',
     'manual'),
]

latex_toplevel_sectioning = 'chapter'
latex_show_pagerefs = True
latex_show_urls = 'footnote'


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'lcode3d', 'LCODE 3D Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'LCODE3D', 'LCODE 3D Documentation',
     author, 'LCODE3D',
     'Quasistatic plasma wakefield simulation code in well under 1000 SLOC.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True
